# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ecc57e10a5e8a4875ab825c45a13f915158b55535200a3d953bf763d871ffefd02606fdb28aa06db0765da50547956c1a910f8ca350934c55413fc4aea6933

test:
  secret_key_base: 81dec18594bd13e8e5e5bf6dde00daf38ebb0e1e076010798f3403fbe587a45708ff786c64b1a56c255bafa1f83287bba5028d2b5870b35bbe1afec6ae14cc1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
